# Generated by Django 5.0.2 on 2024-03-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='image')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', models.CharField(max_length=1000)),
                ('booking_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='recentimage')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', models.CharField(max_length=1000)),
            ],
        ),
    ]
