# Generated by Django 5.0.2 on 2024-09-18 15:30

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='image')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', tinymce.models.HTMLField()),
                ('authorname', models.CharField(blank=True, max_length=50, null=True)),
                ('authorname_hyperlink', models.URLField(blank=True, null=True)),
                ('blog_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='image')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', tinymce.models.HTMLField()),
                ('booking_link', models.URLField(blank=True, null=True)),
                ('EventCreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_year', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
            options={
                'ordering': ['-member_year'],
            },
        ),
        migrations.CreateModel(
            name='RecentEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='recentimage')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', tinymce.models.HTMLField()),
                ('RecentEventCreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='image')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('date_year', models.CharField(blank=True, max_length=20, null=True)),
                ('details_text', models.TextField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('linkedln_link', models.URLField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.members')),
            ],
        ),
    ]
