<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-14 19:53

=======
# Generated by Django 5.0.1 on 2024-03-16 19:28

import django.db.models.deletion
>>>>>>> main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('subject', models.TextField()),
=======
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='image')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('list_text', models.CharField(max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.members')),
>>>>>>> main
            ],
        ),
    ]
