# Generated by Django 5.0.1 on 2024-03-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_members_member_text_members_member_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_detail',
            name='date_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
