# Generated by Django 5.0.2 on 2024-03-22 12:41

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event_eventcreateddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='caption',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recentevent',
            name='caption',
            field=tinymce.models.HTMLField(),
        ),
    ]
