# Generated by Django 5.0.1 on 2024-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_member_detail_date_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_detail',
            old_name='socials_link',
            new_name='instagram_link',
        ),
        migrations.AddField(
            model_name='member_detail',
            name='linkedln_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
