# Generated by Django 5.0.2 on 2024-07-17 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_event_caption_alter_recentevent_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentevent',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='RecentEventComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='recentimage')),
                ('rEvent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.recentevent')),
            ],
        ),
    ]
