# Generated by Django 5.0.1 on 2024-03-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_socials_link_member_detail_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['-member_year']},
        ),
    ]
