# Generated by Django 5.0.1 on 2024-07-11 02:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_members_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='image')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', tinymce.models.HTMLField()),
                ('booking_link', models.URLField(blank=True, null=True)),
                ('EventCreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='recentimage')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', tinymce.models.HTMLField()),
                ('RecentEventCreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member_detail',
            name='details_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
