# Generated by Django 5.0.2 on 2024-03-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event_eventcreateddate_and_more'),
        ('home', '0005_alter_members_options'),
    ]

    operations = [
    ]
