# Generated by Django 5.0.2 on 2024-03-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_event_caption_alter_recentevent_caption'),
        ('home', '0006_merge_20240321_1903'),
    ]

    operations = [
    ]
