# Generated by Django 5.0.1 on 2024-07-26 10:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_event_recentevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='image')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', tinymce.models.HTMLField()),
                ('authorname', models.CharField(blank=True, max_length=50, null=True)),
                ('authorname_hyperlink', models.URLField(blank=True, null=True)),
                ('Blog_Created_Date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
